# Generated by Django 3.1.7 on 2021-04-22 14:20

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.FileField(default='default_user.md', storage=users.models.OverwriteStorage, upload_to=users.models.get_user_document_path),
        ),
    ]
