# Generated by Django 3.1.7 on 2021-06-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210528_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_devices',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='registered_devices'),
        ),
    ]
