# Generated by Django 3.1.7 on 2021-06-11 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210611_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
