# Generated by Django 3.1.7 on 2021-07-26 07:33

import django.core.files.storage
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210619_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_qrcode',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/mediaprotected/', location='/Volumes/1TB/Users/peterbernstein/Django/SpineSplinr/mediaprotected'), upload_to=users.models.username_qrcode),
        ),
    ]
