# Generated by Django 3.2 on 2021-08-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caserooms', '0003_auto_20210528_0508'),
        ('users', '0011_user_login_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='referring_Caseroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caserooms.caseroom'),
        ),
    ]
