# Generated by Django 3.2 on 2021-12-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_consent_referring_caseroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='component_trace',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='next_scheduled_visit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next scheduled visit'),
        ),
    ]
