# Generated by Django 3.2 on 2021-12-27 16:37

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211202_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=users.models.OverwriteStorage, upload_to='avatars/'),
        ),
    ]
