FROM spinesplinr-base:1.0
#FROM python:3.7.6
#ENV PYTHONUNBUFFERED 1
#RUN apt-get update && apt-get install -y libpq-dev gcc python-dev musl-dev

#RUN mkdir /code
#WORKDIR /code
#ADD requirements.txt /code/
ADD requirements-worker-1.0.55.txt /code/
RUN pip install -r requirements-worker-1.0.55.txt
ADD ./ /code/

