# Generated by Django 3.1.7 on 2021-04-01 12:23

from django.db import migrations, models
import splineapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpineSplineCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpineSplineModel',
            fields=[
                ('type', models.CharField(choices=[('dummy', 'dummy'), ('process_xray_cobb', 'process_xray_cobb'), ('process_upright', 'process_upright'), ('process_bendforward', 'process_bendforward')], default='dummy', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('started', 'started'), ('finished', 'finished'), ('failed', 'failed'), ('failed_approval_pending', 'failed: approval is pending'), ('finished_approval_pending', 'finished: approval is pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=50, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('formatted_data', models.JSONField()),
                ('data', models.FileField(blank=True, upload_to=splineapp.models.img_directory_path)),
                ('errors', models.CharField(blank=True, default='', max_length=100)),
                ('img', models.ImageField(default='defaultimg.jpg', upload_to=splineapp.models.img_directory_path)),
                ('modified_img', models.ImageField(default='defaultimg.jpg', upload_to=splineapp.models.img_directory_path)),
            ],
            options={
                'ordering': ['created'],
                'permissions': (('can_see_all_entries', 'Can see all entries'), ('can_supervise_entry', 'Can supervise entry')),
            },
        ),
    ]
