# Generated by Django 3.1.7 on 2021-04-22 14:20

from django.db import migrations, models
import splineapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0002_auto_20210401_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinesplinemodel',
            name='resized_img',
            field=models.ImageField(default='defaultimg.jpg', upload_to=splineapp.models.img_directory_path),
        ),
    ]
