# Generated by Django 3.1.7 on 2021-05-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0003_spinesplinemodel_resized_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='formatted_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
