# Generated by Django 3.1.7 on 2021-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0005_auto_20210510_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinesplinemodel',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
