# Generated by Django 3.1.7 on 2021-05-28 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import splineapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splineapp', '0006_spinesplinemodel_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinesplinecollection',
            name='data',
            field=models.FileField(blank=True, upload_to=splineapp.models.img_directory_path),
        ),
        migrations.AddField(
            model_name='spinesplinecollection',
            name='formatted_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spinesplinecollection',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spinesplinecollection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='spinesplinecollection',
            index=models.Index(fields=['id'], name='splineapp_s_id_a27ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='spinesplinecollection',
            index=models.Index(fields=['owner'], name='splineapp_s_owner_i_4ab78e_idx'),
        ),
        migrations.AddIndex(
            model_name='spinesplinemodel',
            index=models.Index(fields=['id'], name='splineapp_s_id_cceab9_idx'),
        ),
        migrations.AddIndex(
            model_name='spinesplinemodel',
            index=models.Index(fields=['owner'], name='splineapp_s_owner_i_ef9f20_idx'),
        ),
        migrations.AddIndex(
            model_name='spinesplinemodel',
            index=models.Index(fields=['status', 'locked'], name='splineapp_s_status_80b0ba_idx'),
        ),
    ]
