# Generated by Django 3.1.7 on 2021-05-31 05:12

from django.db import migrations, models
import splineapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0007_auto_20210528_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='modified_img',
            field=models.ImageField(default='defaultimg.jpg', storage=splineapp.models.OverwriteStorage, upload_to=splineapp.models.img_directory_path),
        ),
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='resized_img',
            field=models.ImageField(default='defaultimg.jpg', storage=splineapp.models.OverwriteStorage, upload_to=splineapp.models.img_directory_path),
        ),
    ]
