# Generated by Django 3.1.7 on 2021-05-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0008_auto_20210531_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spinesplinemodel',
            name='errors',
        ),
        migrations.AddField(
            model_name='spinesplinemodel',
            name='errors_dict',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
