# Generated by Django 3.1.7 on 2021-06-19 08:36

from django.db import migrations, models
import splineapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0009_auto_20210531_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinesplinemodel',
            name='protected_modified_img',
            field=models.ImageField(default='defaultimg.jpg', storage=splineapp.models.ProtectedOverwriteStorage, upload_to=splineapp.models.img_directory_path),
        ),
        migrations.AddField(
            model_name='spinesplinemodel',
            name='protected_resized_img',
            field=models.ImageField(default='defaultimg.jpg', storage=splineapp.models.ProtectedOverwriteStorage, upload_to=splineapp.models.img_directory_path),
        ),
    ]
