# Generated by Django 3.1.7 on 2021-06-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0010_auto_20210619_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('started', 'started'), ('finished', 'finished'), ('failed', 'failed'), ('failed_approval_pending', 'failed: approval is pending'), ('finished_approval_pending', 'finished: approval is pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('UPLOADED', 'UPLOADED'), ('CROP_LEVEL1', 'CROP_LEVEL1'), ('CLASSIFY_LEVEL1', 'CLASSIFY_LEVEL1'), ('CLASSIFY_LEVEL2', 'CLASSIFY_LEVEL2'), ('MEASURE_LEVEL1', 'MEASURE_LEVEL1'), ('MEASURE_LEVEL2', 'MEASURE_LEVEL2'), ('MEASURE_LEVEL3', 'MEASURE_LEVEL3'), ('PROTECTING', 'PROTECTING'), ('PROTECTED', 'PROTECTED')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='type',
            field=models.CharField(choices=[('dummy', 'dummy'), ('process_xray_cobb', 'process_xray_cobb'), ('process_upright', 'process_upright'), ('process_bendforward', 'process_bendforward'), ('discarded', 'discarded')], default='dummy', max_length=20),
        ),
    ]
