# Generated by Django 3.1.7 on 2021-06-26 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0011_auto_20210621_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spinesplinecollection',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='spinesplinemodel',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='spinesplinecollection',
            name='data',
        ),
        migrations.RemoveField(
            model_name='spinesplinecollection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='spinesplinemodel',
            name='data',
        ),
        migrations.AddField(
            model_name='spinesplinecollection',
            name='diagnosis',
            field=models.CharField(choices=[('NC', 'No Scoliosis from clinical point of view'), ('NR', 'No Scoliosis, radiologically proven'), ('SC', 'Scoliosis from clinical point of view'), ('SR', 'Scoliosis, radiologically proven'), ('U', 'Not sure'), ('P', 'Scoliosis postop'), ('B', 'Scoliosis inbrace')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='spinesplinecollection',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddIndex(
            model_name='spinesplinecollection',
            index=models.Index(fields=['diagnosis'], name='splineapp_s_diagnos_c6ef11_idx'),
        ),
    ]
