# Generated by Django 3.1.7 on 2021-06-26 15:56

from django.db import migrations, models
import splineapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0015_auto_20210626_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinesplinecollection',
            name='formatted_data',
            field=models.JSONField(default=splineapp.models.default_formatted_data),
        ),
    ]
