# Generated by Django 3.1.7 on 2021-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0016_auto_20210626_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinesplinecollection',
            name='formatted_data',
            field=models.JSONField(null=True),
        ),
    ]
