# Generated by Django 3.1.7 on 2021-06-27 06:12

from django.db import migrations, models
import splineapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0017_auto_20210627_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinesplinecollection',
            name='formatted_data',
            field=models.JSONField(default=splineapp.models.default_formatted_data),
        ),
    ]
