# Generated by Django 3.1.7 on 2021-06-29 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0018_auto_20210627_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
