# Generated by Django 3.1.7 on 2021-06-29 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0019_auto_20210629_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='created',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
