# Generated by Django 3.1.7 on 2021-06-29 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0020_auto_20210629_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
