# Generated by Django 3.1.7 on 2021-06-29 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splineapp', '0021_auto_20210629_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpineSplineDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(choices=[('NC', 'No Scoliosis from clinical point of view'), ('NR', 'No Scoliosis, radiologically proven'), ('SC', 'Scoliosis from clinical point of view'), ('SR', 'Scoliosis, radiologically proven'), ('U', 'Not sure'), ('P', 'Scoliosis postop'), ('B', 'Scoliosis inbrace')], default='U', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='spinesplinecollection',
            name='splineapp_s_diagnos_c6ef11_idx',
        ),
        migrations.RemoveField(
            model_name='spinesplinecollection',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='spinesplinediagnosis',
            name='responsible_physician',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__in': users.models.Userrole.isMed}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spinesplinecollection',
            name='diagnoses',
            field=models.ManyToManyField(related_name='collection', to='splineapp.SpineSplineDiagnosis'),
        ),
    ]
