# Generated by Django 3.1.7 on 2021-06-29 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splineapp', '0022_auto_20210629_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinesplinediagnosis',
            name='responsible_physician',
            field=models.ForeignKey(limit_choices_to={'roles__in': users.models.Userrole.isMed}, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='users.user'),
        ),
    ]
