# Generated by Django 3.1.7 on 2021-07-19 16:57

from django.db import migrations, models
import splineapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0026_auto_20210629_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='img',
            field=models.ImageField(default='defaultimg.jpg', max_length=255, upload_to=splineapp.models.img_directory_path),
        ),
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='modified_img',
            field=models.ImageField(default='defaultimg.jpg', max_length=255, storage=splineapp.models.OverwriteStorage, upload_to=splineapp.models.img_directory_path),
        ),
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='protected_modified_img',
            field=models.ImageField(default='defaultimg.jpg', max_length=255, storage=splineapp.models.ProtectedOverwriteStorage, upload_to=splineapp.models.img_directory_path),
        ),
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='protected_resized_img',
            field=models.ImageField(default='defaultimg.jpg', max_length=255, storage=splineapp.models.ProtectedOverwriteStorage, upload_to=splineapp.models.img_directory_path),
        ),
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='resized_img',
            field=models.ImageField(default='defaultimg.jpg', max_length=255, storage=splineapp.models.OverwriteStorage, upload_to=splineapp.models.img_directory_path),
        ),
    ]
