# Generated by Django 3.2 on 2021-10-04 11:01

from django.db import migrations, models
import splineapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0027_auto_20210719_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinesplinemodel',
            name='man_labeled_img',
            field=models.ImageField(default='defaultimg.jpg', max_length=255, storage=splineapp.models.OverwriteStorage, upload_to=splineapp.models.img_directory_path),
        ),
    ]
