# Generated by Django 3.2 on 2021-10-04 11:24

from django.db import migrations, models
import splineapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0028_spinesplinemodel_man_labeled_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinesplinemodel',
            name='protected_man_labeled_img',
            field=models.ImageField(default='defaultimg.jpg', max_length=255, storage=splineapp.models.ProtectedOverwriteStorage, upload_to=splineapp.models.img_directory_path),
        ),
    ]
