# Generated by Django 3.2 on 2021-10-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0029_spinesplinemodel_protected_man_labeled_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinesplinemodel',
            name='status_dict',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
