# Generated by Django 3.2 on 2021-10-13 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splineapp', '0030_spinesplinemodel_status_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpineSplineTherapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy', models.CharField(choices=[('NO', 'No Therapy nor follow-up'), ('RE', 'Wait and Re-Evaluation'), ('P', 'Physiotherapy'), ('NB', 'Night-time brace'), ('DB', 'Full-time brace'), ('S', 'Sugery')], default='NO', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='spinesplinediagnosis',
            name='recommendation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='spinesplinemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('started', 'started'), ('UPLOADED', 'UPLOADED'), ('CROP_LEVEL1', 'CROP_LEVEL1'), ('CLASSIFY_LEVEL1', 'CLASSIFY_LEVEL1'), ('CLASSIFY_LEVEL2', 'CLASSIFY_LEVEL2'), ('MEASURE_LEVEL1', 'MEASURE_LEVEL1'), ('MEASURE_LEVEL2', 'MEASURE_LEVEL2'), ('MEASURE_LEVEL3', 'MEASURE_LEVEL3'), ('PROTECTING', 'PROTECTING'), ('PROTECTED', 'PROTECTED')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ComplianceApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('compliance_witness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_witness', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='spinesplinecollection',
            name='therapy',
            field=models.ManyToManyField(related_name='collection', to='splineapp.SpineSplineTherapy'),
        ),
        migrations.AddField(
            model_name='spinesplinecollection',
            name='therapy_compliance',
            field=models.ManyToManyField(related_name='collection', to='splineapp.ComplianceApproval'),
        ),
    ]
