# Generated by Django 3.2 on 2021-11-09 14:01

from django.db import migrations, models
import splineapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('splineapp', '0031_auto_20211013_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinesplinemodel',
            name='thumb_img',
            field=models.ImageField(default='defaultimg.jpg', max_length=255, storage=splineapp.models.OverwriteStorage, upload_to=splineapp.models.img_directory_path),
        ),
    ]
