# Generated by Django 3.1.7 on 2021-04-24 06:27

import MLModelManager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('type', models.CharField(choices=[('dummy', 'dummy'), ('cropresize_img', 'cropresize_img'), ('categorize_img', 'categorize_img'), ('process_xray_cobb', 'process_xray_cobb'), ('process_upright', 'process_upright'), ('process_bendforward', 'process_bendforward')], default='dummy', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('created', 'created'), ('tested', 'tested'), ('standby', 'standby'), ('busy', 'busy')], max_length=50, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('performance', models.JSONField()),
                ('version', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('modelfile', models.FileField(blank=True, upload_to=MLModelManager.models.model_directory_path)),
                ('codefile', models.FileField(blank=True, upload_to=MLModelManager.models.model_directory_path)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlmodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
