# Generated by Django 3.1.7 on 2021-04-24 09:42

import MLModelManager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MLModelManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='codefile',
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='modelfile',
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'created'), ('tested', 'tested'), ('standby', 'standby'), ('busy', 'busy')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MLFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, storage=MLModelManager.models.OverwriteStorage, upload_to=MLModelManager.models.model_directory_path)),
                ('mlmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MLModelManager.mlmodel')),
            ],
        ),
    ]
