# Generated by Django 3.1.7 on 2021-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLModelManager', '0002_auto_20210424_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='performance',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
