# Generated by Django 3.1.7 on 2021-07-19 09:24

import MLModelManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLModelManager', '0004_auto_20210429_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlfile',
            name='file',
            field=models.FileField(blank=True, upload_to=MLModelManager.models.model_directory_path),
        ),
    ]
