# Generated by Django 3.1.7 on 2021-07-19 16:57

import MLModelManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLModelManager', '0005_auto_20210719_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlfile',
            name='file',
            field=models.FileField(blank=True, max_length=255, storage=MLModelManager.models.OverwriteStorage, upload_to=MLModelManager.models.model_directory_path),
        ),
    ]
