# Generated by Django 3.1.7 on 2021-04-01 12:23

import caserooms.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(default=caserooms.models.get_default_expiry)),
                ('title', models.CharField(blank=True, default='Caseroom', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CaseRoomEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, default='', max_length=400)),
                ('caseroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caserooms.caseroom')),
            ],
        ),
    ]
