# Generated by Django 3.1.7 on 2021-04-01 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caserooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseroomentry',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caseroomentry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseroom',
            name='email_reminder_for_participants',
            field=models.ManyToManyField(blank=True, related_name='caserooms_email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseroom',
            name='members',
            field=models.ManyToManyField(related_name='caserooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseroom',
            name='news_for_participants',
            field=models.ManyToManyField(blank=True, related_name='caserooms_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseroom',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caseroom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='caseroomentry',
            index=models.Index(fields=['id'], name='caserooms_c_id_b42af1_idx'),
        ),
        migrations.AddIndex(
            model_name='caseroom',
            index=models.Index(fields=['id'], name='caserooms_c_id_77c33f_idx'),
        ),
    ]
