# Generated by Django 3.2 on 2021-12-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caserooms', '0003_auto_20210528_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseroom',
            name='title',
            field=models.CharField(blank=True, default='Caseroom', max_length=100),
        ),
    ]
